# Generated by Django 4.2.20 on 2025-05-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_filter_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_filter',
            field=models.CharField(choices=[('amaro', 'Amaro'), ('apollo', 'Apollo'), ('earlybird', 'Earlybird'), ('gotham', 'Gotham'), ('hefe', 'Hefe'), ('hudson', 'Hudson'), ('lily', 'Lily'), ('lofi', 'Lo-Fi'), ('normal', 'Normal'), ('poprocket', 'Poprocket'), ('rise', 'Rise'), ('sutro', 'Sutro'), ('walden', 'Walden'), ('xpro2', 'X-pro II')], default='normal', max_length=32),
        ),
    ]
